#!/usr/bin/env bash
CACHE_FOLDER=$HOME/.config/BraveSoftware
if [[ ! -e ${CACHE_FOLDER} ]]; then
    mkdir ${CACHE_FOLDER};
fi;

CONFIG=${1:-"default"}
#notify-send ${CONFIG}

brave=brave-browser-nightly
if ! command -v $brave >/dev/null  ; then
	brave=brave
fi

$brave --user-data-dir="$CACHE_FOLDER/brave-${CONFIG}-data"

